apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer-binding
  namespace: development
subjects:
- kind: User
  name: deployer
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: deployer-role
  apiGroup: rbac.authorization.k8s.io